export type PriceUnit = "hour" | "service" | "strip" | "component" | "project";

export interface PricingService {
  code: string;
  name: string;
  nameEn: string;
  price: number | null;
  quantifiable: boolean;
  unit: string;
  unitEn: string;
  note?: string;
  noteEn?: string;
}

export interface PricingCategory {
  id: string;
  label: string;
  labelEn: string;
  services: PricingService[];
}

export const PRICING_CATEGORIES: PricingCategory[] = [
  {
    id: "software",
    label: "Software",
    labelEn: "Software",
    services: [
      {
        code: "SW001",
        name: "Instalación de Windows",
        nameEn: "Windows installation",
        price: 15000,
        quantifiable: true,
        unit: "Servicio",
        unitEn: "Service",
        note: "Incluye drivers",
        noteEn: "Drivers included",
      },
      {
        code: "SW002",
        name: "Formateo e instalación de Windows",
        nameEn: "Windows format & installation",
        price: 20000,
        quantifiable: true,
        unit: "Servicio",
        unitEn: "Service",
        note: "Respaldo aparte",
        noteEn: "Backup not included",
      },
      {
        code: "SW003",
        name: "Instalación de Office",
        nameEn: "Office installation",
        price: 5000,
        quantifiable: true,
        unit: "Servicio",
        unitEn: "Service",
        note: "Licencia no incluida",
        noteEn: "License not included",
      },
      {
        code: "SW004",
        name: "Eliminación de virus",
        nameEn: "Virus removal",
        price: 10000,
        quantifiable: true,
        unit: "Servicio",
        unitEn: "Service",
        note: "Según complejidad",
        noteEn: "Depending on complexity",
      },
      {
        code: "SW005",
        name: "Optimización de PC",
        nameEn: "PC optimization",
        price: 10000,
        quantifiable: true,
        unit: "Servicio",
        unitEn: "Service",
        note: "Limpieza de sistema",
        noteEn: "System cleanup",
      },
      {
        code: "SW006",
        name: "Instalación de impresora",
        nameEn: "Printer installation",
        price: 5000,
        quantifiable: true,
        unit: "Servicio",
        unitEn: "Service",
      },
      {
        code: "SW007",
        name: "Configuración de red",
        nameEn: "Network setup",
        price: 10000,
        quantifiable: true,
        unit: "Servicio",
        unitEn: "Service",
      },
      {
        code: "SW008",
        name: "Desarrollo de software",
        nameEn: "Software development",
        price: 15000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "SW009",
        name: "Ajustes de interfaz",
        nameEn: "Interface adjustments",
        price: 10000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
    ],
  },
  {
    id: "hardware",
    label: "Hardware",
    labelEn: "Hardware",
    services: [
      {
        code: "HW001",
        name: "Limpieza interna PC",
        nameEn: "Internal PC cleaning",
        price: 10000,
        quantifiable: true,
        unit: "Servicio",
        unitEn: "Service",
      },
      {
        code: "HW002",
        name: "Cambio de disco SSD",
        nameEn: "SSD replacement",
        price: 12000,
        quantifiable: true,
        unit: "Servicio",
        unitEn: "Service",
        note: "SSD aparte",
        noteEn: "SSD sold separately",
      },
      {
        code: "HW003",
        name: "Cambio de memoria RAM",
        nameEn: "RAM upgrade",
        price: 8000,
        quantifiable: true,
        unit: "Servicio",
        unitEn: "Service",
        note: "RAM aparte",
        noteEn: "RAM sold separately",
      },
      {
        code: "HW004",
        name: "Instalación de luces LED",
        nameEn: "LED lights installation",
        price: 5000,
        quantifiable: true,
        unit: "Tira",
        unitEn: "Strip",
      },
      {
        code: "HW005",
        name: "Diagnóstico de equipo",
        nameEn: "Equipment diagnostics",
        price: 5000,
        quantifiable: true,
        unit: "Servicio",
        unitEn: "Service",
      },
      {
        code: "HW006",
        name: "Mantenimiento preventivo",
        nameEn: "Preventive maintenance",
        price: 15000,
        quantifiable: true,
        unit: "Servicio",
        unitEn: "Service",
      },
      {
        code: "HW007",
        name: "Ensamble de computadora",
        nameEn: "PC assembly",
        price: 25000,
        quantifiable: true,
        unit: "Servicio",
        unitEn: "Service",
      },
      {
        code: "HW008",
        name: "Instalación de componentes",
        nameEn: "Component installation",
        price: 8000,
        quantifiable: true,
        unit: "Componente",
        unitEn: "Component",
      },
    ],
  },
  {
    id: "dev",
    label: "Desarrollo de Software",
    labelEn: "Software Development",
    services: [
      {
        code: "DEV001",
        name: "Desarrollo de software de escritorio",
        nameEn: "Desktop software development",
        price: 10000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "DEV002",
        name: "Desarrollo de aplicación web",
        nameEn: "Web application development",
        price: 18000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "DEV003",
        name: "Desarrollo de API REST",
        nameEn: "REST API development",
        price: 18000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "DEV004",
        name: "Desarrollo de aplicación móvil",
        nameEn: "Mobile app development",
        price: 20000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "DEV005",
        name: "Modificación de sistema existente",
        nameEn: "Modification of existing system",
        price: 12500,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "DEV006",
        name: "Corrección de errores (debugging)",
        nameEn: "Bug fixing (debugging)",
        price: 12000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "DEV007",
        name: "Diseño de base de datos",
        nameEn: "Database design",
        price: 15000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "DEV008",
        name: "Integración con APIs externas",
        nameEn: "External API integration",
        price: 18000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
    ],
  },
  {
    id: "embedded",
    label: "Sistemas Embebidos",
    labelEn: "Embedded Systems",
    services: [
      {
        code: "EMB001",
        name: "Programación de microcontroladores",
        nameEn: "Microcontroller programming",
        price: 20000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "EMB002",
        name: "Diseño de sistemas embebidos",
        nameEn: "Embedded systems design",
        price: 22000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "EMB003",
        name: "Desarrollo de firmware",
        nameEn: "Firmware development",
        price: 22000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "EMB004",
        name: "Comunicación UART, I2C, SPI",
        nameEn: "UART, I2C, SPI communication",
        price: 20000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "EMB005",
        name: "Integración de sensores",
        nameEn: "Sensor integration",
        price: 18000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "EMB006",
        name: "Desarrollo IoT",
        nameEn: "IoT development",
        price: 25000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
    ],
  },
  {
    id: "electronics",
    label: "Electrónica",
    labelEn: "Electronics",
    services: [
      {
        code: "ELE001",
        name: "Diseño esquemático electrónico",
        nameEn: "Electronic schematic design",
        price: 20000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "ELE002",
        name: "Diseño PCB",
        nameEn: "PCB design",
        price: 25000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "ELE003",
        name: "Prototipado electrónico",
        nameEn: "Electronic prototyping",
        price: 18000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
    ],
  },
  {
    id: "web",
    label: "Desarrollo Web",
    labelEn: "Web Development",
    services: [
      {
        code: "WEB000",
        name: "Cambios menores en Sitio Web",
        nameEn: "Minor website changes",
        price: 8000,
        quantifiable: true,
        unit: "Hora",
        unitEn: "Hour",
      },
      {
        code: "WEB001",
        name: "Página web informativa",
        nameEn: "Informational website",
        price: 150000,
        quantifiable: false,
        unit: "Proyecto",
        unitEn: "Project",
      },
      {
        code: "WEB002",
        name: "Landing page",
        nameEn: "Landing page",
        price: 100000,
        quantifiable: false,
        unit: "Proyecto",
        unitEn: "Project",
      },
      {
        code: "WEB003",
        name: "Tienda virtual básica",
        nameEn: "Basic online store",
        price: 300000,
        quantifiable: false,
        unit: "Proyecto",
        unitEn: "Project",
      },
      {
        code: "WEB004",
        name: "Sistema web personalizado",
        nameEn: "Custom web system",
        price: null,
        quantifiable: false,
        unit: "Proyecto",
        unitEn: "Project",
      },
    ],
  },
];

export function getServiceByCode(code: string): PricingService | undefined {
  for (const category of PRICING_CATEGORIES) {
    const found = category.services.find((s) => s.code === code);
    if (found) return found;
  }
  return undefined;
}
